#!/bin/bash

echo "running this post-receive hook"
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo $oldrev
    echo $newrev
    echo $refname
    echo $branch
    if [ "$branch" == "master" ]; then
        # Do something
    fi
done
