#!/bin/bash

# push _site directory to gh-pages
while read oldrev newrev refname
do
  branch=$(git rev-parse --symbolic --abbrev-ref $refname)
  if [ "$branch" == "master" ]; then
    git subtree push --prefix _site origin gh-pages
  fi
done

printf "\n"
