#!/bin/bash

# build categories and sidebar before every commit
python _build/categories.py _posts > categories.md
python _build/sidebar.py _posts > _includes/sidebar.md
git add categories.md _includes/sidebar.md
