#!/bin/bash -e

# the -e flag in the shebang line ensures that this hook exits if any of its commands exits with a non-zero exit status

# build categories and sidebar before every commit
python _build/categories.py _posts > categories.md
python _build/sidebar.py _posts > _includes/sidebar.md
git add categories.md _includes/sidebar.md
