# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dronfelipe
description: > # this means to ignore newlines until "baseurl:"
  Code, TILs, and other stuff.
baseurl: "/posts" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: KyleBebak
github_username: kylebebak
# makes sure links are the same as they are in github repo
permalink: /:categories/:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM
